Update url David.json
jocnunez/FP-2DAW-DAW pull request #14
Opened 2023-11-16 16:44 UTC by david2o3

2023-11-16 17:22 UTC, jocnunez requested changes

2023-11-16 17:22 UTC, jocnunez commented on urls.json
> +    {
te faltaría añadir la coma antes del objeto, para mantener la estructura del json

2023-11-20 19:22 UTC, david2o3 commented on urls.json
> +    {
Creo que ya lo he hecho Jose. El miércoles me dices!

2023-11-20 22:56 UTC, jocnunez approved these changes

2023-11-20 22:57 UTC, merged